# Base configs
baseurl: "https://nana.fakrulafif.web.id"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Fakrul - Afif"
subtitle: "Lihat dunia melalui mata saya!"
author: "Nana"
header:
 title: "Foto Nana"
 subtitle: "by Fakrul - Afif"
footer:
 name: "Hai, nama saya Nana"
 bio: "Saya seorang pembangun dan peminat teknologi dari Malaysia. Suka membuat aplikasi kecil kecil menyelesaikan masalah kecil dalam hidup dan kini belajar fotografi."
 github: "Inginkan laman web seperti ini untuk diri sendiri secara percuma? Hanya <a href=\"https://github.com/ramswaroop/photography\">fork repo ini pada github</a> ;)"
web_design: "FakrulDev"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/rullshz"
  tiktok: "https://www.tiktok.com/rulshz"
  WhatsApp: "https://wa.me/601159754638"
  github: "https://www.github.com/fahrihostingg"
